// Phase 1.9.4 AI clerk — PDF renderer.
//
// Takes the markdown summary from Claude and renders it into a clean PDF
// that matches Bulldog's visual tone (dark accent on header, light body).
// We use pdfkit because it's pure JS (no native deps, plays nice on Render)
// and parse markdown by hand — full markdown support is overkill and the
// summarizer's output structure is predictable enough.

import PDFDocument from "pdfkit";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { randomUUID } from "node:crypto";

export interface RenderPdfOpts {
  title: string;
  markdown: string;
  attendees: Array<{ name: string; email?: string | null }>;
  channelName: string;
  contractTitle?: string | null;
  contractAppUrl?: string | null;
  startedAt: Date;
  endedAt: Date;
  aiGenerated: boolean;
}

export interface RenderPdfResult {
  filePath: string;
  sizeBytes: number;
}

const BULLDOG_ACCENT = "#1f4ed8";   // brand blue
const BODY_DARK = "#0f172a";        // slate-900
const BODY_LIGHT = "#475569";       // slate-600
const RULE = "#e2e8f0";             // slate-200

export async function renderMeetingNotesPdf(opts: RenderPdfOpts): Promise<RenderPdfResult> {
  const tmpPath = path.join(os.tmpdir(), `meeting-notes-${randomUUID()}.pdf`);
  const doc = new PDFDocument({
    size: "LETTER",
    margins: { top: 64, bottom: 64, left: 64, right: 64 },
    info: {
      Title: opts.title,
      Author: "Bulldog Chat AI Clerk",
      Subject: opts.contractTitle || opts.channelName,
      CreationDate: opts.endedAt,
    },
  });

  const stream = fs.createWriteStream(tmpPath);
  doc.pipe(stream);

  // Header band
  doc.rect(0, 0, doc.page.width, 90).fill(BULLDOG_ACCENT);
  doc.fillColor("#ffffff");
  doc.fontSize(10).font("Helvetica").text("BULLDOG CHAT  ·  MEETING NOTES", 64, 32, { characterSpacing: 1.5 });
  doc.fontSize(18).font("Helvetica-Bold").text(opts.title, 64, 50, { width: doc.page.width - 128, lineBreak: false, ellipsis: true });

  doc.fillColor(BODY_DARK);
  doc.y = 120;

  // Metadata block
  doc.fontSize(10).font("Helvetica").fillColor(BODY_LIGHT);
  const metaRows: Array<[string, string]> = [
    ["Channel", opts.channelName],
  ];
  if (opts.contractTitle) metaRows.push(["Linked contract", opts.contractTitle]);
  metaRows.push(["Start", opts.startedAt.toLocaleString()]);
  metaRows.push(["End", opts.endedAt.toLocaleString()]);
  const durSec = Math.max(0, Math.round((opts.endedAt.getTime() - opts.startedAt.getTime()) / 1000));
  metaRows.push(["Duration", formatDuration(durSec)]);
  metaRows.push(["Attendees", opts.attendees.map(a => a.name).join(", ") || "—"]);
  metaRows.push(["Generated by", opts.aiGenerated ? "Claude (Anthropic)" : "Bulldog Chat (fallback)"]);

  for (const [label, value] of metaRows) {
    const startY = doc.y;
    doc.font("Helvetica-Bold").fillColor(BODY_DARK).text(label, 64, startY, { width: 110, continued: false });
    doc.font("Helvetica").fillColor(BODY_LIGHT).text(value, 180, startY, { width: doc.page.width - 64 - 180 });
    doc.y = Math.max(doc.y, startY + 14);
  }

  // Rule
  doc.moveDown(0.5);
  doc.strokeColor(RULE).lineWidth(0.75).moveTo(64, doc.y).lineTo(doc.page.width - 64, doc.y).stroke();
  doc.moveDown(0.75);

  // Body — render markdown
  renderMarkdown(doc, opts.markdown);

  // Footer (last page)
  const footer = `Bulldog Chat · meeting notes generated ${new Date().toLocaleString()} · channel: ${opts.channelName}`;
  doc.fontSize(8).font("Helvetica").fillColor(BODY_LIGHT)
    .text(footer, 64, doc.page.height - 50, { width: doc.page.width - 128, align: "center" });

  doc.end();

  await new Promise<void>((resolve, reject) => {
    stream.on("finish", () => resolve());
    stream.on("error", reject);
  });

  const stat = fs.statSync(tmpPath);
  return { filePath: tmpPath, sizeBytes: stat.size };
}

function formatDuration(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  if (h > 0) return `${h}h ${m}m ${s}s`;
  if (m > 0) return `${m}m ${s}s`;
  return `${s}s`;
}

// Tiny, pragmatic markdown renderer — enough for the summarizer's output:
//   # H1 / ## H2 / ### H3   → sized headings, blue for H1
//   - bullet                → indented "• " lines
//   1. ordered              → indented "N." lines
//   **bold** _italic_       → toggled inline styles
//   ```code```              → mono block with subtle background
// Anything else lands as a body paragraph.
function renderMarkdown(doc: PDFKit.PDFDocument, md: string) {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  let inCode = false;
  let codeBuffer: string[] = [];

  const flushCode = () => {
    if (codeBuffer.length === 0) return;
    const text = codeBuffer.join("\n");
    doc.moveDown(0.3);
    const startY = doc.y;
    doc.fontSize(9).font("Courier").fillColor(BODY_DARK);
    const heightEstimate = doc.heightOfString(text, { width: doc.page.width - 128 - 16 });
    // background
    doc.rect(64, startY, doc.page.width - 128, heightEstimate + 16).fillColor("#f1f5f9").fill();
    doc.fillColor(BODY_DARK).text(text, 72, startY + 8, { width: doc.page.width - 128 - 16 });
    doc.moveDown(0.4);
    codeBuffer = [];
  };

  for (const raw of lines) {
    const line = raw.replace(/\t/g, "  ");

    if (line.trim().startsWith("```")) {
      if (inCode) { flushCode(); inCode = false; } else { inCode = true; }
      continue;
    }
    if (inCode) { codeBuffer.push(line); continue; }

    if (line.trim() === "") {
      doc.moveDown(0.4);
      continue;
    }

    // Headings
    if (/^###\s+/.test(line)) {
      doc.moveDown(0.3);
      doc.fontSize(11).font("Helvetica-Bold").fillColor(BODY_DARK);
      drawInline(doc, line.replace(/^###\s+/, ""), { width: doc.page.width - 128 });
      doc.moveDown(0.1);
      continue;
    }
    if (/^##\s+/.test(line)) {
      doc.moveDown(0.4);
      doc.fontSize(13).font("Helvetica-Bold").fillColor(BODY_DARK);
      drawInline(doc, line.replace(/^##\s+/, ""), { width: doc.page.width - 128 });
      doc.moveDown(0.1);
      continue;
    }
    if (/^#\s+/.test(line)) {
      doc.moveDown(0.5);
      doc.fontSize(15).font("Helvetica-Bold").fillColor(BULLDOG_ACCENT);
      drawInline(doc, line.replace(/^#\s+/, ""), { width: doc.page.width - 128 });
      doc.fillColor(BODY_DARK);
      doc.moveDown(0.1);
      continue;
    }

    // Bullets
    const bulletMatch = line.match(/^(\s*)[-*]\s+(.*)/);
    if (bulletMatch) {
      const indent = Math.min(3, Math.floor(bulletMatch[1].length / 2));
      const x = 64 + indent * 12;
      doc.fontSize(10).font("Helvetica").fillColor(BODY_DARK);
      const startY = doc.y;
      doc.text("•", x, startY, { continued: false });
      doc.fontSize(10).font("Helvetica");
      drawInline(doc, bulletMatch[2], { x: x + 12, y: startY, width: doc.page.width - 64 - (x + 12) });
      doc.moveDown(0.1);
      continue;
    }
    const olMatch = line.match(/^(\s*)(\d+)\.\s+(.*)/);
    if (olMatch) {
      const indent = Math.min(3, Math.floor(olMatch[1].length / 2));
      const x = 64 + indent * 12;
      doc.fontSize(10).font("Helvetica").fillColor(BODY_DARK);
      const startY = doc.y;
      doc.text(`${olMatch[2]}.`, x, startY, { continued: false });
      drawInline(doc, olMatch[3], { x: x + 20, y: startY, width: doc.page.width - 64 - (x + 20) });
      doc.moveDown(0.1);
      continue;
    }

    // Body paragraph
    doc.fontSize(10).font("Helvetica").fillColor(BODY_DARK);
    drawInline(doc, line, { width: doc.page.width - 128 });
    doc.moveDown(0.1);
  }

  if (inCode) flushCode();
}

// Render a single line with inline **bold** and _italic_ toggles. We split
// the line into segments and adjust the font for each. pdfkit lets us
// stream segments via continued:true.
function drawInline(
  doc: PDFKit.PDFDocument,
  text: string,
  opts: { x?: number; y?: number; width: number }
) {
  const segments = parseInline(text);
  let isFirst = true;
  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i];
    if (seg.bold && seg.italic) doc.font("Helvetica-BoldOblique");
    else if (seg.bold) doc.font("Helvetica-Bold");
    else if (seg.italic) doc.font("Helvetica-Oblique");
    else doc.font("Helvetica");

    const isLast = i === segments.length - 1;
    const passedOpts: any = { width: opts.width, continued: !isLast };
    if (isFirst && opts.x != null && opts.y != null) {
      doc.text(seg.text, opts.x, opts.y, passedOpts);
    } else {
      doc.text(seg.text, passedOpts);
    }
    isFirst = false;
  }
  // Reset to default after the line.
  doc.font("Helvetica");
}

function parseInline(text: string): Array<{ text: string; bold: boolean; italic: boolean }> {
  // Greedy left-to-right. Supports **bold** and _italic_ (and *italic*).
  // Doesn't try to be fancy — overlapping tokens get treated as plain text.
  const out: Array<{ text: string; bold: boolean; italic: boolean }> = [];
  let i = 0;
  let bold = false;
  let italic = false;
  let buf = "";
  const flush = () => { if (buf) { out.push({ text: buf, bold, italic }); buf = ""; } };
  while (i < text.length) {
    if (text.startsWith("**", i)) { flush(); bold = !bold; i += 2; continue; }
    if (text[i] === "_" || text[i] === "*") { flush(); italic = !italic; i += 1; continue; }
    buf += text[i++];
  }
  flush();
  return out.length > 0 ? out : [{ text, bold: false, italic: false }];
}
